### ISSUE TITLE
Why this is deprecated?

### ISSUE THREAD

**Issue by jdnichollsc** [FormidableLabs/whackage#34]
Hello guys,
This is just a question, are you using other tool to manage multiple repositories like meta or bit?

**Comment by boygirl** [comment]
@jdnichollsc we consider this project "archived", so Formidable is no longer spending any resources developing or maintaining this project. We chose to do this because: 
1) The project is not very active (less than 100 weekly npm downloads, not a lot of recent issues / PRs) 
2) None of our devs are super excited to invest their time into this project
3) We wanted to make time for more new projects :)

**Comment by jdnichollsc** [comment]
cool, thanks for your comments!
On the other hand, are you guys already using Bit? :)
