### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by segalr3** [FormidableLabs/whackage#6]
I followed the instructions, however I can't get it to work properly. 
whackage detects the file changes, but still I need to kill the whack/npm server each time I make a change, otherwise it won't reload the changes.

**Comment by jevakallio** [comment]
Hi @segalr3! I think this might be an issue with the React Native packager: https://github.com/facebook/react-native/issues/13019

The [proposed fix](https://github.com/facebook/react-native/commit/570c564e77d00bbbc090acd047f04779914a5d9c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) for that is in marked for rc-0.44, but seems to match the configuration on 0.43 stable, so perhaps this is already fixed in React Native 0.43?

**Comment by segalr3** [comment]
Hi @jevakallio, thanks for the quick reply!
It might be fixed on RN 0.43, we are still on 0.42. What version do you guys use?

**Comment by jevakallio** [comment]
I'm currently not using whackage (using monorepo so no need) on my current project, which is still on 0.42.

If you upgrade to 0.43, please let me know if this issue is fixed!

**Comment by bitcrumb** [comment]
I had the same issue and can confirm that it is fixed in react 0.43.0. Keep on whacking!

**Comment by jevakallio** [comment]
@bitcrumb thanks for reporting - closing this as resolved upstream in RN 0.43

**Comment by segalr3** [comment]
Confirm that it is fixed in react 0.43.0.
Thanks great package!
